### ISSUE TITLE
Attributes of Pack component is not getting locked in OneOps when provisioned from boo

### ISSUE THREAD

**Issue by Mahesha1991** [oneops/boo#67]
Version : boo-task:0.30.0
The attributes of Pack components were getting locked in OneOps.

Version: boo-task:0.58.0
The attributes of Pack components are NOT getting locked in OneOps.

This is an important functionality for us and it is missing in the newer version.
Issue with this is, if someone does a pack pull, the attributes which are not locked in OneOps, will be overwritten from the pack which is very critical(bug) for our application.

Example : "Solr version : 6.4.0 (OneOps attribute not locked)"
In the pack the "Solr version is : 7.6.0" If a pack pull is done, it will overwrite the attribute ("Solr version") in OneOps which is not expected.

**Comment by vinayrao92** [comment]
The latest release version of boo (1.0.18) does lock the attributes in OO design. Moreover this is handled by the OneOps-api, not boo. The attributes were never locked in transition phase in OneOps via boo. Because boo always executes the entire OO lifecycle for any changes (design-->transition-->operate).
So your pull pack (design stage) should work without overriding your locked attributes.
Platform Attributes which are mentioned in your boo script, those are by default locked in your design.

**Comment by vinayrao92** [comment]
This is not a boo error, like mentioned above it is because @Mahesha1991 is using a concord-boo-plugin which has a older version of oneops.client.version (5.0.19), the newer release version (5.0.21) fixes this problem by retaining / adding the parent attributes during platform updates. 

@mosabua : i believe we can close this issue.

**Comment by mosabua** [comment]
So can the concord plugin get a newer Jar added?
